import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

export default defineConfig([
    ...nextVitals,
    ...nextTs,
    globalIgnores([
        // Build output and generated files
        ".next/**",
        "src/prisma/openapits.d.ts",   // generated by `pnpm run db:generate` — linting it is noise
        "next.config.ts",
    ]),
    {
        rules: {
            "object-curly-spacing": ["error", "always"],
            "indent": ["error", 4],
        },
        
    },
    {
        files: ["src/components/ui/**"],
        rules: { "react-hooks/set-state-in-effect": "off", "react-hooks/purity": "off", "@next/next/no-img-element": "off" },
    }
]);