import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

export default defineConfig([
    ...nextVitals,
    ...nextTs,
    globalIgnores([
        // Build output and generated files
        ".next/**",
        "src/prisma/openapits.d.ts",   // generated by `pnpm run db:generate` — linting it is noise
    ]),
    {
        rules: {
            "object-curly-spacing": ["error", "always"],
            "indent": ["error", 4],
        },
    },
]);