import createClient from "openapi-fetch";
import type { paths } from "@/prisma/openapits"; // generated by openapi-typescript

export const client = createClient<paths>({ baseUrl: "" });
export type { paths } from "@/prisma/openapits";