import createClient from "openapi-fetch";
import type { paths, components } from "@/prisma/openapits"; // generated by openapi-typescript

export const client = createClient<paths>({ baseUrl: "" });
export type ApiTypes = components["schemas"]
export type { paths } from "@/prisma/openapits";