import { PrismaClient } from '@prisma/client'
import { PrismaPg } from '@prisma/adapter-pg'

// Inside docker, the DB is reachable under the compose service name
if (process.env.DB_HOST && process.env.DATABASE_URL) {
    process.env.DATABASE_URL = process.env.DATABASE_URL.replace(/@([^:/]+)/, `@${process.env.DB_HOST}`);
}

const globalForPrisma = global as unknown as { 
    prisma: PrismaClient
}

const connectionString = `${process.env.DATABASE_URL}`

const adapter = new PrismaPg({ connectionString });
const prisma = globalForPrisma.prisma || new PrismaClient({ adapter })

if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma

export default prisma

import createClient from "openapi-fetch";
import type { paths } from "@/prisma/openapits"; // generated by openapi-typescript

export const client = createClient<paths>({ baseUrl: process.env.URL });
export type { paths } from "@/prisma/openapits";
